### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by egeorjon** [egeorjon/GoLyat#14]
See [Blogy](https://blogy-blog-template.webflow.io/) for the [style guide](https://blogy-blog-template.webflow.io/template-info/style-guide) page.

* 3 to 4 colors max,
* the text color is equal to the darker background color,
* Title are in the same colors than the text (even when they are links)
* One of the color is very very light

Possible palettes
* [Coolors 1](https://coolors.co/e63946-f1faee-a8dadc-457b9d-1d3557)
* [Coolors 2](https://coolors.co/palette/2b2d42-8d99ae-edf2f4-ef233c-d90429)

##Todo

**Way 1**

* [x] Setup Primary, secondary color,
* [x] Check the consequences,

**Way 2**

* [x] Search the term `color` in the Boostrap variables file,
* [x] Set these variables to the theme color.
