### ISSUE TITLE
Head

### ISSUE THREAD

**Issue by egeorjon** [egeorjon/GoLyat#15]
## Todo

* [x] Internal templates vs theme templates: improve: .Site.Params.OpenGraph = Internal | theme | none (default internal)
* [x] Same for Twitter, Facebook, Schema,
* [x] RSS feeds => lien vers la section, et/ou (?) vers la home ?
* [x] manifest file (can we rename the file after the processing ? automatically ?)

## Documentation

* [Head](https://htmlhead.dev/)
* [Get the last post of a section](https://discourse.gohugo.io/t/solved-get-the-first-and-last-post-in-a-section-date-based/6734/10)

## Sub-pages / metalinks

Avec Google, vous verrez quelques sous-pages pertinentes de MDN listées sous le lien de la page d'accueil — ce sont des liens du site ; ils sont configurables dans les outils de [Google's webmaster tools](https://www.google.com/webmasters/tools/) - ces outils sont donc un moyen de rendre les résultats de recherche de votre site meilleurs avec le moteur de recherche de Google.

## CleanWhite [#](https://github.com/zhaohuabing/hugo-theme-cleanwhite/blob/master/layouts/partials/head.html)

```Go
<!--  Custom CSS  -->
    {{ range .Site.Params.custom_css -}}
    <link rel="stylesheet" href="{{ . | absURL }}">
    {{- end }}
```
Same for JS.

```Go
{{ if .Params.thumbnail }}
    <meta property="og:image" content="{{ .Site.BaseURL }}{{ .Params.thumbnail }}">
    <meta property="twitter:image" content="{{ .Site.BaseURL }}{{ .Params.thumbnail }}" />
    {{ else }}
    <meta property="og:image" content="{{ .Site.BaseURL }}/{{ .Site.Params.header_image }}">
    <meta property="twitter:image" content="{{ .Site.BaseURL }}/{{ .Site.Params.header_image }}" />
    {{ end }}
```
Same for title, description, ...

## Universal

Use of their own code for Facebook and Twitter. 

## Ananke [#](https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/_default/baseof.html)

Check if we are on production or not.
