### ISSUE TITLE
Share links

### ISSUE THREAD

**Issue by egeorjon** [egeorjon/GoLyat#4]
## List of media to be implemented

| In the scope | Don't know | Out of the scope |
|---------------|--------------|--------------------|
| Facebook | Tumblr | Youtube |
| Twitter | Instagram | TikTok |
| LinkedIn | | Reddit |
| Pinterest | | |
| Whatapps | | |

## Todo

* [x] Tests
* [x] Review the list of media (Wix, Tumblr, Dig, really used ?
* [x]  Be careful about the icons
* [x] Review the Facebook link
* [x] Remove Whatsapp from the list => Move to the next version

## Technical part

* [CSS-Tricks](https://css-tricks.com/simple-social-sharing-links/)

### Facebook

| Purpose | Parameter |
|---------|-----------|
| URL (of course) | u |
| custom image | picture |
| custom title | title |
| custom quote | quote |
| custom description | description |
| caption (aka website name) | caption |

```HTML
https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fstackoverflow.com%2Fq%2F20956229%2F1101509&picture=http%3A%2F%2Fwww.applezein.net%2Fwordpress%2Fwp-content%2Fuploads%2F2015%2F03%2Ffacebook-logo.jpg&title=A+nice+question+about+Facebook&quote=Does+anyone+know+if+there+have+been+recent+changes+which+could+have+suddenly+stopped+this+from+working%3F&description=Apparently%2C+the+accepted+answer+is+not+correct.
```
